import "@/app/globals.scss";
import { SiteProvider } from "@/context/SiteContext";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { i18n } from "@/dictionaries/i18n.config";
import { getDictionary } from "@/helpers/getDictionary";

export const metadata = {
  title: "MALOV&PARTNERS",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body>
        <SiteProvider>
          <Header lang={lang} dictionary={dictionary} />
          <main>{children}</main>
          <Footer lang={lang} dictionary={dictionary} />
        </SiteProvider>
      </body>
    </html>
  );
}
